FROM buildpack-deps:yakkety

# Create user
RUN groupadd -r app && useradd -r -g app app

# Create app directory
RUN mkdir -p /app
WORKDIR /app

# Install library dependencies
RUN apt-get update && apt-get install -y \
  build-essential \
  cmake \
  libxmlrpc-c++8-dev \
 && rm -rf /var/lib/apt/lists/*

# Bundle app source
COPY . /app

# Build app
RUN ./compile

# Switch to user
USER app

# Set data location
VOLUME ["/data"]

ENTRYPOINT [ "./client" ]
