FROM ruby:2.3

# Create user
RUN groupadd -r app && useradd -r -g app app

# Create app directory
RUN mkdir -p /app
WORKDIR /app

# Bundle app source
COPY . /app

# Build app
RUN ./compile

# Switch to user
USER app

# Set data location
VOLUME ["/data"]

ENTRYPOINT [ "./client" ]
